### ISSUE TITLE
Labels with a very large value break container builds

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#506] opened 2019-05-02 19:55 UTC
**Describe the bug**
If the image.yaml descriptor has a very huge label value it will make cekit build fails (tested with docker and osbs and podman).

Apparently, the label string value are being parsed to bytes somewhere and this issue happens: 
https://pastebin.com/fG2EdUKP

I tried to do this, but the build failed with "Docker unknown instruction":

`if line != build_log[-1]:
    if isinstance(line, bytes): 
        line = line.decode('utf-8') `

With podman, this issue happens:

> Error: error building at step {Env:[USER_NAME=apb USER_UID=1001 BASE_DIR=/opt/apb HOME=/opt/apb PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=oci JBOSS_IMAGE_NAME=rhpam-7/rhpam-apb JBOSS_IMAGE_VERSION=1.1] Command:label Args:[] Flags:[] Attrs:map[] Message:LABEL  Original:LABEL }: LABEL requires at least one argument

**To reproduce**
use a image.yaml file descriptor with this label:
https://pastebin.com/CbbxgMGm

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.
https://pastebin.com/fG2EdUKP

**Environment information:**
 - Operating system: Fedora 29
 - CEKit version: 3.0.1

**Additional context**
This label is a requirement to work with APB (ansible playbook bundle)

**Comment by ruromero** [comment] 2019-05-02 20:33
@spolti It is not related to cekit but to dockerfiles themselves. I had this same issue and could reproduce it directly with Docker and Podman

**Comment by spolti** [comment] 2019-05-02 20:36
How did you fix it?

**Comment by ruromero** [comment] 2019-05-02 20:43
> How did you fix it?

With some refactoring in the apb descriptor. The limit cannot be avoided AFAIK

**Comment by spolti** [comment] 2019-05-02 21:08
Actually it can be fixed on cekit side.
To properly fix it, the label should not be configured in one single line, but in multiple lines, like:

`      com.redhat.apb.spec=\
"line1\
line2/
...
line N"`


Just made a manual test with the Dockerfile and worked.


@goldmann can we make cekit limit the line size of the label to make it render the label in the Dockerfile similar than above?

**Comment by spolti** [comment] 2019-05-02 22:12
@goldmann 
found a workaround: https://pastebin.com/cwXXX4y5

With it I could at least build the image with no issue.

But the squas step failed, now sure why or if it is related with the changes above: https://pastebin.com/gWNHNk0j

**Comment by ruromero** [comment] 2019-05-03 07:36
I think it should be fixed in the script that encodes the apb.yml file. It is explicitly doing it in a single line
https://github.com/ansibleplaybookbundle/rhpam-apb/blob/master/prepare.sh#L3
However it is great to have cekit preventing this issue.

**Comment by goldmann** [comment] 2019-05-07 11:34
Thanks for reporting this, I'll take a look and get back to you.

**Comment by goldmann** [comment] 2019-05-07 12:58
For reference: https://github.com/docker/for-linux/issues/157#issuecomment-342657035

**Comment by goldmann** [comment] 2019-05-09 09:58
I'm investigating further what I stated in my previous comment about failures. I'm preparing a minimal reproducer to actually understand the issue.

**Comment by goldmann** [comment] 2019-05-09 13:10
I have reproduced the failure, without a very long label. Opened: https://github.com/goldmann/docker-squash/issues/181 to track this.

**Comment by spolti** [comment] 2019-05-09 22:36
Thanks @goldmann.

**Comment by goldmann** [comment] 2019-05-14 08:09
My statement in comment above (https://github.com/cekit/cekit/issues/506#issuecomment-490897567) wasn't correct. The failures I saw were not related to the length of the label, but it was an issue with marker files in docker-squash.

**Comment by ricardozanini** [comment] 2019-05-21 15:31
I'm also facing the same error with the APB builds. Unfortunately the `prepare.sh` from the APB repo is not working, because when I added more characters to the apb.yaml file, the generated Dockerfile had a large label value. Looks like I reached the buffer limit. 

After applying [this patch](https://pastebin.com/cwXXX4y5), worked like a charm. If you needed one more test case to prove that the patch works, you have it. :)

**Comment by goldmann** [comment] 2019-05-21 15:36
Right, I do feel that we are still trying to workaround an issue that should be solved somewhere else. 

Saying this, I'm happy to make your life easier.

If you guys can prepare a PR with the code change and a test that would cover it, then I would be happy to review it.

**Comment by goldmann** [comment] 2019-05-21 15:37
One more thing, if you manage to submit this soon, then I'll make sure it will land in 3.1 planned for (more or less) next week.

**Comment by ricardozanini** [comment] 2019-05-21 15:38
As soon as I finish this new APB build that I giving me headaches!

**Comment by ricardozanini** [comment] 2019-05-27 14:06
@goldmann just sent a PR, whenever you have the time could you please review? Many thanks!

**Closed** 2019-05-27 14:39 UTC
Labels: complexity/low, priority/medium, type/bug
