### ISSUE TITLE
Support to pass _UrlResource to fetch-artifacts-url.yaml

### ISSUE THREAD

**Issue by hmlnarik** [cekit/cekit#643] opened 2020-01-03 14:43 UTC
**Describe the solution you'd like**
Currently, only `_PlainResource` can be converted to `fetch-artifacts-url.yaml` ([ref](https://github.com/cekit/cekit/blob/develop/cekit/generator/osbs.py#L78-L79)). Any resource that is not published in Brew and can be obtained in build time via url, could be passed to `fetch-artifacts-url.yaml` just the same. This seems to be a straightforward and helpful enhancement that would help decreasing size of dist-git repositories that sometimes have to check in huge files due to this restriction.

Is this restriction intentional? Could the support for `_UrlResource` be added as well?

**Additional context**
dist-git repositories are growing beyond any limits.

**Comment by goldmann** [comment] 2020-01-07 10:08
@hmlnarik I think the code could be changed to support URL artifacts as well. The downside I see is that OSBS does not allow for fetching **any** artifacts defined as URL, instead there are only specific hosts allowed (whitelist). This means that if there is a URL added for which the host is not whitelisted, OSBS build will fail.

If such change would be incorporated, then responsibility for making sure the URL is allowed would be on the developer side since CEKit would not be able to validate it.

I think the root cause of the issue (growing dist-git repository) is that commits were pushed some time ago by accident with the binary files (artifacts). CEKit does many things to prevent it from being added to dist-git and instead pushing these artifacts to dist-git lookaside cache, but I'm not sure how bullet proof it was earlier.

**Comment by hmlnarik** [comment] 2020-01-07 15:27
Thank you @goldmann, this is certainly an acceptable limitation, and the feature would be appreciated!

**Comment by goldmann** [comment] 2020-01-08 11:28
Let's schedule it tentatively for 3.7.0.

**Comment by rnc** [comment] 2021-02-11 09:27
I think this is resolved with #661. Can you try upgrading and see if this works for you?

**Closed by rnc** 2021-02-11 09:27 UTC
Labels: status/review, type/enhancement
