### ISSUE TITLE
tox -e py38 failed about cekit@4.8.0 on centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [cekit/cekit#861] opened 2023-07-03 09:41 UTC
**Describe the bug**
hello, I meet a problem:tox -e py38 failed about cekit@4.8.0 on centos8_aarch64

### Steps to reproduce the issue
```console
command:tox -e py38
ERROR    cekit:cli.py:516 There are no content_sets defined for platform 'aarch64'!
Traceback (most recent call last):
  File "/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/cekit/cli.py", line 502, in run
    command.execute()
  File "/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/cekit/builder.py", line 69, in execute
    self.generate()
  File "/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/cekit/builder.py", line 121, in generate
    self.generator.generate()
  File "/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/cekit/generator/base.py", line 191, in generate
    self.prepare_repositories()
  File "/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/cekit/generator/base.py", line 459, in prepare_repositories
    url = self._prepare_content_sets(
  File "/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/cekit/generator/base.py", line 489, in _prepare_content_sets
    raise CekitError(
cekit.errors.CekitError: There are no content_sets defined for platform 'aarch64'!

errors:

======================================================================================== short test summary info =========================================================================================
FAILED tests/test_dockerfile.py::test_dockerfile_docker_odcs_pulp - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_assume_yes - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_process_error - assert 'A GIT ERROR' in 'INFO     cekit:cli.py:422 Using OSBS builder to build the image\nDEBUG    cekit:cli.py:454 Running version 4.8.0\nDEBUG    cekit:cli.py:467 Configuring CEKit...\nINFO     c...
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_push_with_sync_only - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_kick_build_without_push - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_kick_build_with_push - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_help_file - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_extra_files - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_extra_files_with_extra_dir_target - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_extra_files_non_default_with_extra_dir_target - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_extra_files_and_overwrite - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_extra_files_from_custom_dir - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_extra_default - FileNotFoundError: [Errno 2] No such file or directory: '/home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/.tox/py38/tmp/test_osbs_builder_extra_defaul0/source/...
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_files_to_dist_git_when_it_is_a_directory - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_artifact_directory_to_dist_git_when_it_already_exists - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_add_files_to_dist_git_without_dotgit_directory - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_koji_target_based_on_branch - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_koji_target_in_descriptor - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_plain_file_creation - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_1[flag1] - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_2 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_3 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_4 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_5 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_multiple_hash - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_naming - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_creation_naming_with_target - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_validate_dockerfile - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_removal - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_source_fail - assert 'Unable to add source-url for artifact' in 'INFO     cekit:cli.py:422 Using OSBS builder to build the image\nDEBUG    cekit:cli.py:454 Running version 4.8.0\nDEBUG    cekit:cli.py:467 Config...
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_source_1 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_url_file_source_2 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_pnc_file_removal - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_container_yaml_existence[flag1] - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_cachito_enabled - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_rhpam_1 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_rhpam_3 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_pnc_file_creation_1 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_fetch_artifacts_pnc_file_creation_2 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_with_brew_and_lookaside - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_kick_build_with_tag_1 - assert 1 == 0
FAILED tests/test_integ_builder_osbs.py::test_osbs_builder_kick_build_with_tag_2 - assert 1 == 0
FAILED tests/test_integ_multi_stage.py::test_multi_stage_single_image_in_list - assert 1 == 0
FAILED tests/test_integ_multi_stage.py::test_multi_stage_proper_image - assert 1 == 0
FAILED tests/test_integ_multi_stage.py::test_multi_stage_with_scratch_target_image - assert 1 == 0
FAILED tests/test_integ_podman.py::test_podman_operator_metadata - assert 1 == 0
FAILED tests/test_qa.py::test_formatting - Failed: Command: /home/stage/root/spack-stage-py-cekit-4.8.0-b7kl53mxxtuc5i2nzf2bqcd7cn7ubcug/spack-src/support/run_formatter.py --check
FAILED tests/test_unit_tools.py::test_get_image_version_fails - FileNotFoundError: [Errno 2] No such file or directory: 'skopeo'
FAILED tests/test_unit_tools.py::test_run_wrapper_whitespace - cekit.errors.CekitError: Exception running subprocess
FAILED tests/test_unit_tools.py::test_run_wrapper_no_capture - cekit.errors.CekitError: Exception running subprocess
FAILED tests/test_validate.py::test_content_sets_file_container_file - assert 1 == 0
FAILED tests/test_validate.py::test_content_sets_file_container_embedded - assert 1 == 0
FAILED tests/test_validate.py::test_content_sets_embedded_container_embedded - assert 1 == 0
FAILED tests/test_validate.py::test_content_sets_embedded_container_file - assert 1 == 0
FAILED tests/test_validate.py::test_simple_image_build - assert 1 == 0
=================================================================== 55 failed, 271 passed, 27 skipped, 5 warnings in 148.31s (0:02:28) ===================================================================
```
Can you tell me how to solve these problems?

### Information on your system
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original

**Comment by Tom-python0121** [comment] 2023-07-04 03:23
I found that the x86_64 platform also reported a similar error.
```console
Traceback (most recent call last):
  File "/home/stage/root/spack-stage-py-cekit-master-g5swjcw6llxq3hsfz4kjsz5dqlmzyveu/spack-src/cekit/cli.py", line 502, in run
    command.execute()
  File "/home/stage/root/spack-stage-py-cekit-master-g5swjcw6llxq3hsfz4kjsz5dqlmzyveu/spack-src/cekit/builder.py", line 61, in execute
    self.before_generate()
  File "/home/stage/root/spack-stage-py-cekit-master-g5swjcw6llxq3hsfz4kjsz5dqlmzyveu/spack-src/cekit/builder.py", line 116, in before_generate
    self.dependency_handler.handle(self.generator, self.params)
  File "/home/stage/root/spack-stage-py-cekit-master-g5swjcw6llxq3hsfz4kjsz5dqlmzyveu/spack-src/cekit/tools.py", line 656, in handle
    self._handle_dependencies(o.dependencies(params))
  File "/home/stage/root/spack-stage-py-cekit-master-g5swjcw6llxq3hsfz4kjsz5dqlmzyveu/spack-src/cekit/tools.py", line 545, in _handle_dependencies
    self._check_for_executable(dependency, executable, package)
  File "/home/stage/root/spack-stage-py-cekit-master-g5swjcw6llxq3hsfz4kjsz5dqlmzyveu/spack-src/cekit/tools.py", line 596, in _check_for_executable
    raise CekitError(msg)
cekit.errors.CekitError: CEKit dependency: 'brew' was not found, please provide the 'brew' executable. To satisfy this requirement you can install the 'brewkoji' package.
```

**Comment by jmtd** [comment] 2023-07-04 09:11
The error in the first message seems completely different to the second message. In the second message, it's not clear to me what command you ran which provoked the error; can you share that please?

**Comment by Tom-python0121** [comment] 2023-07-04 09:17
I also run the tox -e py38 command on x86_64

**Comment by rnc** [comment] 2023-07-04 10:31
@Tom-python0121 Why are you attempting to run the unit tests? Have you followed the installation instructions (See https://docs.cekit.io/en/latest/handbook/installation/instructions.html ) and installed all third party software that CEKit (and the unit tests) will require?

**Comment by rnc** [comment] 2023-07-06 08:25
I'm closing this as your first issue is not a bug but a unsupported test platform and the second looks like you ran on a different platform but hadn't followed the documentation. 

If you have any further comments please feel free to reopen/comment or open another issue.

**Closed by rnc** 2023-07-06 08:25 UTC
Labels: type/bug, status/review
