### ISSUE TITLE
ValueError: dictionary update sequence element #12 has length 1; 2 is required

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#450] opened 2019-03-20 15:42 UTC
With [this image source](https://github.com/jmtd/openjdk/tree/rhel8-2k19) (branch rhel8-2k19, commit 503685f9621f91183a1d9fcfcf65cbe8f5745b84) and [this module cloned locally](https://github.com/jmtd/cct_module/tree/rhel82k19) (branch rhel82k1 commit d5e432eeedc503ca2c68744d0167741b0bbd54a9), I get the following when I try `cekit build --overrides-file rhel8-jdk11-overrides.yaml docker`, using cekit develop HEAD=`16489fa42ec264613b91217d1f719c8c702ea1ef`:

```
2019-03-20 15:40:29,115 cekit        WARNING  You are running unreleased development version of CEKit, use it only at your own risk!
Traceback (most recent call last):
  File "/home/ce/cekit/develop/bin/cekit", line 11, in <module>
    load_entry_point('cekit==3.0.dev0', 'console_scripts', 'cekit')()
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/cli.py", line 106, in build_docker
    run_build(ctx, 'docker')
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/cli.py", line 280, in run_build
    run_command(ctx, builder_impl)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/cli.py", line 249, in run_command
    Cekit(common_params).run(clazz, params)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/cli.py", line 333, in run
    command = clazz(self.params, params)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/builders/docker_builder.py", line 49, in __init__
    super(DockerBuilder, self).__init__('docker', common_params, params)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/builder.py", line 50, in __init__
    super(Builder, self).__init__(self.build_engine, Command.TYPE_BUILDER)
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/builder.py", line 20, in __init__
    self.dependency_handler = DependencyHandler()
  File "/home/ce/cekit/develop/lib/python2.7/site-packages/cekit/tools.py", line 161, in __init__
    self.os_release = dict(l.strip().split('=') for l in content)
ValueError: dictionary update sequence element #12 has length 1; 2 is required

```

**Comment by goldmann** [comment] 2019-03-20 15:45
Can you paste your `/etc/os-release` file content?

**Comment by goldmann** [comment] 2019-03-21 08:33
I couldn't reproduce it on Fedora 29 nor Ubuntu. This must have something to do with the `/etc/os-release` I asked about above. Could you please paste it?

The code there is parsing the operating system information and is failing at it. It needs to be fixed.

----

Besides this, your build will not work with CEKit 3.0, because support for old-type repositories is now removed (see https://github.com/cekit/cekit/issues/386):

```yaml
packages:
  repositories:
  - ubi8
```

Instead you should use:

```yaml
packages:
  content_sets:
    x86_64:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms 
osbs:
  configuration:
    container:
      compose:
        pulp_repos: true
        include_unpublished_pulp_repos: true
```

This also means that this PR should be merged: https://github.com/jboss-openshift/cct_module/pull/334.

**Comment by goldmann** [comment] 2019-03-21 09:17
I can reproduce it on RHEL 7.

**Comment by goldmann** [comment] 2019-03-21 09:17
Following content is failing the build:

```properties
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 Beta (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7 Beta"
```

**Comment by goldmann** [comment] 2019-03-21 09:19
RHEL 8 UBI is failing the same way, working on a fix.

**Closed** 2019-03-26 14:16 UTC
Labels: complexity/low, priority/medium, type/bug

**Comment by jmtd** [comment] 2019-04-01 10:06
Hi,

> Besides this, your build will not work with CEKit 3.0, because support for old-type repositories is now removed (see #386):

The reason we have the old scheme in still is we have not found a valid content sets setting for RHEL8 that works for images newer than the beta. The only working sets we have found so far are "rhel-8-for-x86_64-baseos-beta-rpms" etc., in particular

```
packages:
  content_sets:
    x86_64:
      - rhel-8-for-x86_64-baseos-rpms
```

does not work (Cannot create content set: 'Error while generating compose: Failed to find all the content_sets [u'rhel-8-for-x86_64-baseos-rpms', 'rhel-8-for-x86_64-appstream-rpms'] in the Pulp, found only [])

Therefore we are stuck with cekit 2.x until we have working contents sets.

**Comment by goldmann** [comment] 2019-04-01 10:08
You missed the OSBS `configuration` section above, which is crucial to make the content sets work. The example above is fully working.

**Comment by goldmann** [comment] 2019-04-01 10:14
One more note; the `include_unpublished_pulp_repos` will work fine if you build in OSBS with any CEKit version. If you are interested in local builds with hidden content sets, you should use CEKit 3.x (see: https://github.com/cekit/cekit/pull/435).

**Comment by jmtd** [comment] 2019-04-03 09:03
> You missed the OSBS configuration section above, which is crucial to make the content sets work. The example above is fully working.

Thanks, that sorted it!
