### ISSUE TITLE
Remove tests output from disk

### ISSUE THREAD

**Issue by rwngwn** [cekit/cekit#129] opened 2017-11-16 14:51 UTC
Test runs are logging containers output to target/test/output dir. We should disable it and put output to junit results only.

**Comment by dbecvarik** [comment] 2018-01-04 15:07
This is part of concreate test steps - so its need to be fixed there

**Comment by dbecvarik** [comment] 2018-07-24 08:46
This is tricky because outide of CI its hard to read junit output manually.. Maybe we can run some server which will show junit results in html?

**Comment by rcernich** [comment] 2018-07-24 13:35
I don't have any issues with the information being there.  it's easy enough to rm and I don't think it takes up that much space.  That said, if we can consolidate all of the output into the results.xml files, that would be great (so you don't have to look back and forth and figure out which output file goes with which test).

**Comment by rnc** [comment] 2021-02-23 21:12
@goldmann Apart from `target/junit-py37.xml` I am not seeing this. Shall we close this?

**Comment by rnc** [comment] 2022-12-05 11:54
Closing this as not enough details to reproduce.

**Closed by rnc** 2022-12-05 11:54 UTC
Labels: type/enhancement, priority/low, complexity/low
