### ISSUE TITLE
package repositories should be processed during build, not generate

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#66] opened 2017-09-22 22:59 UTC
Because the repositories are only required during the image build and they are specified through the configuration, I think it makes sense to copy them only when doing the build.  This will allow for generation of the image and details without including any sensitive information, e.g. using chained builds in openshift (generate -> build), where the generated code lives in an image that is fed into the docker build.

Therefore, if we're doing just a generate, we should key off the repositories section of the packages element and use that when generating the Dockerfile.  During the build, the user will have to copy the relevant files into the Dockerfile/../repos/ folder, as necessary.

**Comment by dbecvarik** [comment] 2017-09-26 11:14
Generate should prepare everything to build image. Target directory structure is considered implementation detail and no one should mess with it - we do not document how it works and one of the feature is that we can change how target directory is created in future version.
Also we support OSBS as different build and we will soon support buildah ( with kpod and cri-o maybe there will be no docker soon in Kubernetes/OpenShift) as build engine which can again change structure of target directory for these builders in future. Dockerfile is probably only of supported use cases and we should not design any specific work-flow to this.
User should be interested in sources and finalized image only. The generated stuff should not be altered as it can break reproducible builds. 

Running concreate with same descriptor and same configuration should result in completely same image every time.

**Comment by rcernich** [comment] 2017-09-26 12:30
Agreed, but the repo files are not part of the image definition, but are injected via the configuration mechanism.  This differs from other artifacts used to create the image.

This issue was uncovered while putting together a template and chained build for use in openshift.  Because a two step process was used, generate -> build, it meant that the repo files would be stored in the image with the generated artifacts.  I'm guessing this is not desirable, since the idea is that the repo files would be contributed through a secret/config map.  I don't know how sensitive this information is.  The main reason for separating it is because it appears specific to the build and not the image (i.e. contributed via .concreate vs. image.yaml).

**Comment by dbecvarik** [comment] 2017-09-26 12:45
Specific repo files are probably needed only in our use cases, because we are using internal repositories instead of official RHEL ones. So we need to hide these urls. If you are on subscribed RHEL system on OCP installation - you shouldn't need any of these repo files, because you can just enable corresponding subscription/repositories on your RHEL host and this repositories are then accessible in containers.

**Comment by rcernich** [comment] 2017-09-26 12:48
We might want to consider how we manage these in the yaml files, since we're using --enablerepo with the repository name when we generate the image.  This would imply the repo name we use in the yaml file would need to match what's installed on the system.  Are these names standaradized?  Or, should we not be specifying repo names at all in packages?

**Comment by goldmann** [comment] 2017-09-26 13:02
This is something that will change, there will be no "--enablerepo" switches at all.

**Comment by rcernich** [comment] 2017-09-26 18:30
I think we do need to keep a way for adding additional repositories that may be required for building.  For example, a required repository may be disabled or non-existent on the host machine.

**Comment by goldmann** [comment] 2017-09-27 10:43
This is not doable. Some repositories will be always required, but at the same time these will not be public. This is something that will be solved using internal documentation.

**Comment by rcernich** [comment] 2017-09-27 14:32
That would address this issue then.

**Comment by dbecvarik** [comment] 2018-05-07 11:18
This issue should be resolved by repository changes in Cekit 2.0. WE now use all repositories that exists in the image plus the ones we explicitly configure via url/ODCS/package name.

**Closed by dbecvarik** 2018-05-07 11:18 UTC
Labels: bug
